export const products = [
  // Categoría: Alimentos
  {
    id: "01",
    title: "Croquetas para perro",
    price: 25.99,
    stock: 100,
    description: "Alimento seco balanceado para perros adultos de todas las razas.",
    category: "Alimentos",
    imageUrl: "",
  },
  {
    id: "02",
    title: "Croquetas para gato",
    price: 22.99,
    stock: 100,
    description: "Alimento seco con alto contenido en proteínas para gatos adultos.",
    category: "Alimentos",
    imageUrl: "",
  },
  {
    id: "03",
    title: "Snacks para perro",
    price: 8.99,
    stock: 100,
    description: "Premios masticables con sabor a pollo y carne.",
    category: "Alimentos",
    imageUrl: "",
  },
  {
    id: "04",
    title: "Snacks para gato",
    price: 7.99,
    stock: 100,
    description: "Bocaditos de salmón y atún para gatos.",
    category: "Alimentos",
    imageUrl: "",
  },

  // Categoría: Accesorios
  {
    id: "05",
    title: "Collar para perro",
    price: 12.99,
    stock: 50,
    description: "Collar ajustable de nylon con hebilla de seguridad.",
    category: "Accesorios",
    imageUrl: "",
  },
  {
    id: "06",
    title: "Collar para gato",
    price: 10.99,
    stock: 50,
    description: "Collar con cascabel y diseño ajustable para gatos.",
    category: "Accesorios",
    imageUrl: "",
  },
  {
    id: "07",
    title: "Correa para perro",
    price: 15.99,
    stock: 50,
    description: "Correa de nylon resistente con gancho de metal.",
    category: "Accesorios",
    imageUrl: "",
  },
  {
    id: "08",
    title: "Juguete mordedor",
    price: 9.99,
    stock: 50,
    description: "Juguete de goma para perros con diseño de hueso.",
    category: "Accesorios",
    imageUrl: "",
  },

  // Categoría: Higiene
  {
    id: "09",
    title: "Arena para gatos",
    price: 18.99,
    stock: 70,
    description: "Arena aglomerante para la bandeja sanitaria de gatos.",
    category: "Higiene",
    imageUrl: "",
  },
  {
    id: "10",
    title: "Shampoo para perros",
    price: 14.99,
    stock: 70,
    description: "Shampoo antipulgas con ingredientes naturales.",
    category: "Higiene",
    imageUrl: "",
  },
  {
    id: "11",
    title: "Toallitas húmedas",
    price: 8.99,
    stock: 70,
    description: "Toallitas para limpieza de patas y pelaje.",
    category: "Higiene",
    imageUrl: "",
  },
  {
    id: "12",
    title: "Cortaúñas para mascotas",
    price: 11.99,
    stock: 70,
    description: "Cortaúñas seguro y fácil de usar para perros y gatos.",
    category: "Higiene",
    imageUrl: "",
  },

  // Categoría: Camas y Transportadoras
  {
    id: "13",
    title: "Cama para perro",
    price: 29.99,
    stock: 40,
    description: "Cama acolchonada para perros de tamaño mediano.",
    category: "Camas y Transportadoras",
    imageUrl: "",
  },
  {
    id: "14",
    title: "Cama para gato",
    price: 24.99,
    stock: 40,
    description: "Cama suave y confortable para gatos.",
    category: "Camas y Transportadoras",
    imageUrl: "",
  },
  {
    id: "15",
    title: "Transportadora para perro",
    price: 39.99,
    stock: 40,
    description: "Transportadora de plástico resistente con ventilación lateral.",
    category: "Camas y Transportadoras",
    imageUrl: "",
  },
  {
    id: "16",
    title: "Transportadora para gato",
    price: 34.99,
    stock: 40,
    description: "Transportadora portátil con puerta segura para gatos.",
    category: "Camas y Transportadoras",
    imageUrl: "",
  }
];
